name: Lint
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
